services:
  docs:
    image: poker_club_manager_local_docs
    container_name: poker_club_manager_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./poker_club_manager:/app/poker_club_manager:z
    ports:
      - '9000:9000'
    command: /start-docs
